root: /
permalink: /:year-:month/:title/
markdown: rdiscount
highlighter: null
paginate: 5

# Setup
title:            'C++ Actor Framework &mdash; Dev Blog'
tagline:          'The developer blog of the <a href="http://actor-framework.org/" target="_blank">C++ Actor Framework</a>.'
description:      'An Open Source implementation of the actor model in C++'
url:              'http://actor-framework.org/'
baseurl:          /

# owner information
owner:
  name:           C++ Actor Framework
  twitter:        actor_framework
  github:         actor-framework

# post per page
paginate:         3

# Custom vars
version:           0.11.0

# repository
github:
  repo:           https://github.com/actor-framework

# google analytics
google_analytics:
  id: UA-56404861-1
  username: auto

authors:
  dominik:
    display_name: Dominik Charousset
    email: dominik.charousset@haw-hamburg.de
    github: Neverlord
