# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CAF
tagline:          'An Open Source Implementation of the actor model in C++'
description:      'The developer blog of the <a href="http://actor-framework.org/" target="_blank">C++ Actor Framework</a>.'
url:              'http://actor-framework.org/'
baseurl:          /

# owner information
owner:
  name:           C++ Actor Framework
  twitter:        actor_framework
  github:         actor-framework

# post per page
paginate:         3

# Custom vars
version:           0.11.0

# repository
github:
  repo:           https://github.com/actor-framework

# google analytics
google_analytics:
  id: #
  username: #
